### ISSUE TITLE
Error During Evaluation with OGB Datasets

### ISSUE THREAD

**Issue by WWWzq-01** [jeongminpark417/GIDS#13]
When I run `python homogeneous_train_baseline.py` using OGB datasets, I encounter an error with the code:
```python
  out_label = torch.index_select(label_array, 0, b[0]).flatten()
```
The error is that b is undefined and label_array is None.

**Comment by WWWzq-01** [comment]
I use this code to generate `node_feat.npy` and `edge_index.npy`.Is that right?
```python
from ogb.nodeproppred import NodePropPredDataset
import numpy as np

dataset = NodePropPredDataset(name = 'ogbn-products',root='/home/wzq/datasets/OGB')

graph, label = dataset[0] # graph: library-agnostic graph object


features = graph['node_feat'].astype(np.float32)
np.save('/home/wzq/datasets/OGB/ogbn_products/'+'node_feat.npy',features)

edge_index = graph['edge_index']
np.save('/home/wzq/datasets/OGB/ogbn_products/'+'edge_index.npy',edge_index)

```

**Comment by jeongminpark417** [comment]
Sorry for the first error. The dataloader was deprecated for flexibility and the example code was not updated.  You can just remove the line and use the same label checking for IGB. I pushed the updated version to the repo. Keep in mind that the label checking is currently executed in CPU, so it takes a long time to compute the accuracy.

We have not tested with ogbn_product dataset, but the way you generate node_feat.npy and edge_index seem correct to me. Make sure that the edge_index is in COO fromat.

**Comment by jeongminpark417** [comment]
For ogbn dataset, there might be /raw/node_feat.npy and /raw/edge_index.npy file in your root directory ('/home/wzq/datasets/OGB'), depending on your OGB version. If you have these files, you do not need to regenerate them.

**Comment by WWWzq-01** [comment]
Actually, I have tested the ogbn-papers100M dataset, but I am currently using the ogbn-products dataset due to its faster processing speed, which helps in verifying the correctness of the edge_index. Now, the edge_index of the products seems to be correct, as per the igb_small dataset comparison.
<img width="658" alt="image" src="https://github.com/jeongminpark417/GIDS/assets/52373880/b3beb3d2-5f33-4e84-ad64-c1ebb95e6832">
Then, I removed the line and used the same label checking method for IGB. However, the accuracy is only around 2%.

As you mentioned,
> "The dataloader was deprecated for flexibility and the example code was not updated,"

does that mean the dataloader is not suitable for OGB datasets?"

**Comment by jeongminpark417** [comment]
The current dataloader can be used for OGB dataset as well. The only thing that you need to double-check is the format of labels. 

From OGBN_papers100M, we achieved around 17~20% accuracy. If you are getting low accuracy, I recommend you to run the baseline (the version that using mmap) to make sure that the accuracy is high. The batch size or sampling parameters might be too high for smaller datasets, such as ogbn_products. Also, make sure that you are using the correct num_classes flag.

**Comment by WWWzq-01** [comment]
<img width="678" alt="image" src="https://github.com/jeongminpark417/GIDS/assets/52373880/603d2984-2728-40b8-a152-c6238e2dbea5">

Labels are generated using the code in the figure

**Comment by jeongminpark417** [comment]
I just pushed the updated version for dataloader. You should load the node_lable.npy from the dataset.

 if(self.data == 'OGB'):
          path = osp.join(self.dir, 'node_label.npy')
          node_labels = np.load(path).flatten()
          return node_labels

**Comment by WWWzq-01** [comment]
Thank you. For the ogbn-products, I get 30% accuracy. It seems normal.

**Comment by KYUNGSOO-LEE** [comment]
Hi @WWWzq-01 

I am evaluating OGBN datasets.
How to create 'node_label.npy'?

I look forward to your reply.

**Comment by WWWzq-01** [comment]
Hi @KYUNGSOO-LEE 

I use the following code to save 'node_label.npy'
```
from ogb.nodeproppred import NodePropPredDataset
import numpy as np

dataset = NodePropPredDataset(name = 'ogbn-papers100M',root='/data1/datasets/')

graph, label = dataset[0] 
np.save('/mnt/datasets/OGB/ogbn_papers100M/raw/'+'node_label.npy',label)

features = graph['node_feat'].astype(np.float32)
np.save('/mnt/datasets/OGB/ogbn_papers100M/raw/'+'node_feat.npy',features)

 edge_index = graph['edge_index']
np.save('/mnt/ogbn_papers100M/raw/'+'edge_index.npy',edge_index)
```

**Comment by KYUNGSOO-LEE** [comment]
Hi @WWWzq-01 

Thank you for reply. :)

I created numpy files. But for the ogbn-papers100M, I get 2~3% accuracy. 

I don't know why accuracy is low.

Would you share the write dataset script and benchmark script?

Below is my script. 
''''
../bam/build/bin/nvm-readwrite_stripe-bench --input /mnt/nvme14/kslee_backup/workspace/datasets/ogbn_papers100M/node_feat.npy --queue_depth 1024 --access_type 1 --num_queues 128 --threads 102400 --n_ctrls 1 --ioffset 128
'''
'''
TORCH_USE_CUDA_DSA=1 CUDA_LAUNCH_BLOCKING=1 CUDA_VISIBLE_DEVICES=0 python homogenous_train.py --data OGB --model_type sage --path /mnt/nvme14/kslee_backup/workspace/datasets/ogbn_papers100M --GIDS --batch_size 1024 --cache_size $((4*1024))  --num_ele $((550*1000*1000*1024))  --num_ssd 1 --page_size 4096 --window_buffer --wb_size 8 --emb_size 128 --epochs 1 --pin_file /mnt/nvme14/kslee_backup/workspace/datasets/ogbn_papers100M/pr_papers100M.pt --accumulator  --num_classes 172 --hidden_channels 256 --dataset_size papers100M 
'''
Please share the script.
