### ISSUE TITLE
The accuracy is abnormal, when test bam and GIDS under Igbh-small datasets

### ISSUE THREAD

**Issue by smallgrape14** [jeongminpark417/GIDS#18]
I encountered a similar problem to [issues/12](https://github.com/jeongminpark417/GIDS/issues/12)
- I also use the script from the evaluation directory to assess both Bam and GIDS under the igbh-small dataset (type=heterogeneous,download from [there](https://github.com/IllinoisGraphBenchmark/IGB-Datasets) )
- Below is the script that I used for testing Bam and GIDS:

(1)
`write_data.sh` is :
```
CUDA_VISIBLE_DEVICES=0 python tensor_write.py --path /small/processed/paper/node_feat.npy  --cache_size $((4*1024)) --num_ssd 1 --num_ele $((4*1000*1000*1024)) --page_size 4096 --ssd_list 0  --offset 128
```
```
... small/processed/author/node_feat.npy ...
```
```
...small/processed/fos/node_feat.npy ...
```
```
...small/processed/institute/node_feat.npy ... 
```
- the output of `write_data.sh` is shown as below:
- ![image](https://github.com/jeongminpark417/GIDS/assets/60038680/19028eab-2cd0-4e6c-a0b1-d267af298053)
- ![image](https://github.com/jeongminpark417/GIDS/assets/60038680/6d7b01b5-df5b-430b-b362-a2190bcfdaff)
- ![image](https://github.com/jeongminpark417/GIDS/assets/60038680/0c46a646-a25b-443b-b7bb-384b360e2501)
- ![image](https://github.com/jeongminpark417/GIDS/assets/60038680/eb4fb742-323f-4647-95a4-9d4a02dbace7)

(2)
`run_Bam_IGB.sh` is :
```
CUDA_VISIBLE_DEVICES=0  python /GIDS/evaluation/heterogeneous_train.py --dataset_size small --path /datasets/igb_datasets/   --epochs 1 --log_every 1000 --uva_graph 1 --batch_size 1024  --data IGB --model_type rsage --num_layers 3 --fan_out '10,5,5' --cache_size $((4*1024)) --num_ssd 1   --num_ele $((4*1000*1000*1024)) --page_size 4096 --emb_size 1024  --pin_file pr_full.pt --offset 128
```
- the output of `run_Bam_IGB.sh` is shown as below:
- ![image](https://github.com/jeongminpark417/GIDS/assets/60038680/9984ae3a-6562-428c-91de-5ac0a11fdb6b)
- ![image](https://github.com/jeongminpark417/GIDS/assets/60038680/7d1e028b-b374-4a23-b165-a36cb43ad3f1)

(3)
`run_GIDS_IGB.sh` is :
```
CUDA_VISIBLE_DEVICES=0  python heterogeneous_train.py --dataset_size small --path //datasets/igb_datasets/   --epochs 1 --log_every 1000 --uva_graph 1 --GIDS --batch_size 1024  --data IGB --model_type rsage --num_layers 3 --fan_out '10,5,5' --cache_size $((4*1024)) --num_ssd 1  --num_ele $((4*1000*1000*1024)) --page_size 4096 --emb_size 1024 --pin_file pr_full.pt --offset 128 --window_buffer --wb_size 8 --accumulator 
```
- the output of `run_GIDS_IGB.sh` is shown as below:
- ![image](https://github.com/jeongminpark417/GIDS/assets/60038680/3c3b71c2-edad-45d2-a96f-d8066408335a)
- ![image](https://github.com/jeongminpark417/GIDS/assets/60038680/6d06f001-1260-48ff-b0fe-7fc57861d58c)

I want to know why the accuracy is so low, if the parameters are set incorrectly？ Thank you !!!

PS: I have tried the same testing operations under igb-small datasets , the accuracy is normal (around 70%).

**Comment by WWWzq-01** [comment]
It is possible that the write commands in subsequent '*feat.npy' files have overwritten the write command of the previous one. These write commands should have different offsets, such as offset=0, 1000000, 1000000+1926066, 1000000 + 1926066 + 190449.

**Comment by smallgrape14** [comment]
I modify the  write_data.sh  as below:
```
CUDA_VISIBLE_DEVICES=0 python tensor_write.py --path /home/ubuntu/xyp/datasets/igb_datasets/small/processed/paper/node_feat.npy  --cache_size $((4*1024)) --num_ssd 1   --num_ele $((4*1000*1000*1024)) --page_size 4096 --ssd_list 0  --offset 0
CUDA_VISIBLE_DEVICES=0 python tensor_write.py --path /home/ubuntu/xyp/datasets/igb_datasets/small/processed/author/node_feat.npy  --cache_size $((4*1024)) --num_ssd 1   --num_ele $((4*1000*1000*1024)) --page_size 4096 --ssd_list 0  --offset $((1000000))
CUDA_VISIBLE_DEVICES=0 python tensor_write.py --path /home/ubuntu/xyp/datasets/igb_datasets/small/processed/fos/node_feat.npy  --cache_size $((4*1024)) --num_ssd 1   --num_ele $((4*1000*1000*1024)) --page_size 4096 --ssd_list 0 --offset $((1000000+1926066))
CUDA_VISIBLE_DEVICES=0 python tensor_write.py --path /home/ubuntu/xyp/datasets/igb_datasets/small/processed/institute/node_feat.npy  --cache_size $((4*1024)) --num_ssd 1   --num_ele $((4*1000*1000*1024)) --page_size 4096 --ssd_list 0 --offset $((1000000+1926066+190449))
```
the output error such as (GPUassert: an illegal memory access was encountered...) :
![image](https://github.com/jeongminpark417/GIDS/assets/60038680/cb846d2e-117c-4e66-a9cf-0a4841881a8b)
![image](https://github.com/jeongminpark417/GIDS/assets/60038680/bafb8630-5845-4fe1-b556-0cc527a84e0b)

What's wrong?

**Comment by smallgrape14** [comment]
I modify the write_data.sh :
```
CUDA_VISIBLE_DEVICES=0 python tensor_write.py --path /home/ubuntu/xyp/datasets/igb_datasets/small/processed/paper/node_feat.npy  --cache_size $((4*1024)) --num_ssd 1   --num_ele $((4*1000*1000*1024)) --page_size 4096 --ssd_list 0  --offset 0
CUDA_VISIBLE_DEVICES=0 python tensor_write.py --path /home/ubuntu/xyp/datasets/igb_datasets/small/processed/author/node_feat.npy  --cache_size $((4*1024)) --num_ssd 1   --num_ele $((4*1000*1000*1024)) --page_size 4096 --ssd_list 0  --offset $((1000000))
CUDA_VISIBLE_DEVICES=0 python tensor_write.py --path /home/ubuntu/xyp/datasets/igb_datasets/small/processed/fos/node_feat.npy  --cache_size $((4*1024)) --num_ssd 1   --num_ele $((4*1000*1000*1024)) --page_size 4096 --ssd_list 0 --offset $((1000000+1926066))
CUDA_VISIBLE_DEVICES=0 python tensor_write.py --path /home/ubuntu/xyp/datasets/igb_datasets/small/processed/institute/node_feat.npy  --cache_size $((4*1024)) --num_ssd 1   --num_ele $((4*1000*1000*1024)) --page_size 4096 --ssd_list 0 --offset $((1000000+1926066+190449))
```
And I run the write_data.sh ,the output is :
![image](https://github.com/jeongminpark417/GIDS/assets/60038680/1ce972a7-b309-45d3-b1f4-ec6156895857)
But test the Bam and GIDS ,the accuracy is still low

**Comment by WWWzq-01** [comment]
Can you try to use readwrite benchmark in bam repository to write the file into a SSD? This is my [write_data.sh](https://github.com/WWWzq-01/GIDS_Test/blob/master/igbh_small/write_data.sh)
```shell
/home/wzq/GIDS/bam/build/bin/nvm-readwrite_stripe-bench --input /home/wzq/datasets/igbh_datasets/small/processed/paper/node_feat.npy --queue_depth 1024 --access_type 1 --num_queues 128 --threads 102400 --n_ctrls 1 --ioffset 128

/home/wzq/GIDS/bam/build/bin/nvm-readwrite_stripe-bench --input /home/wzq/datasets/igbh_datasets/small/processed/author/node_feat.npy  --queue_depth 1024 --access_type 1 --num_queues 128 --threads 102400 --n_ctrls 1 --ioffset 128 --loffset $((1000000*4096))

/home/wzq/GIDS/bam/build/bin/nvm-readwrite_stripe-bench --input /home/wzq/datasets/igbh_datasets/small/processed/fos/node_feat.npy --queue_depth 1024 --access_type 1 --num_queues 128 --threads 102400 --n_ctrls 1 --ioffset 128 --loffset $((2926066*4096)) 

/home/wzq/GIDS/bam/build/bin/nvm-readwrite_stripe-bench --input /home/wzq/datasets/igbh_datasets/small/processed/institute/node_feat.npy --queue_depth 1024 --access_type 1 --num_queues 128 --threads 102400 --n_ctrls 1 --ioffset 128 --loffset $((3116515 * 4096)) 
```

**Comment by smallgrape14** [comment]
I try use readwrite benchmark to write data into SSD , the command as below:
```
/home/ubuntu/xyp/GIDS/bam/build/bin/nvm-readwrite_stripe-bench --input /home/ubuntu/xyp/datasets/igb_datasets/small/processed/paper/node_feat.npy --queue_depth 1024 --access_type 1 --num_queues 128 --threads 102400 --n_ctrls 1 --ioffset 128

/home/ubuntu/xyp/GIDS/bam/build/bin/nvm-readwrite_stripe-bench --input /home/ubuntu/xyp/datasets/igb_datasets/small/processed/author/node_feat.npy  --queue_depth 1024 --access_type 1 --num_queues 128 --threads 102400 --n_ctrls 1 --ioffset 128 --loffset $((1000000*4096))

/home/ubuntu/xyp/GIDS/bam/build/bin/nvm-readwrite_stripe-bench --input /home/ubuntu/xyp/datasets/igb_datasets/small/processed/fos/node_feat.npy --queue_depth 1024 --access_type 1 --num_queues 128 --threads 102400 --n_ctrls 1 --ioffset 128 --loffset $((2926066*4096)) 

/home/ubuntu/xyp/GIDS/bam/build/bin/nvm-readwrite_stripe-bench --input /home/ubuntu/xyp/datasets/igb_datasets/small/processed/institute/node_feat.npy --queue_depth 1024 --access_type 1 --num_queues 128 --threads 102400 --n_ctrls 1 --ioffset 128 --loffset $((3116515 * 4096)) 
```
Part of the extracted results are as follows:
- for fos/node_feat.npy :
![image](https://github.com/jeongminpark417/GIDS/assets/60038680/60b91ec5-9dcd-4753-8c96-d1d74ff6aa97)
![image](https://github.com/jeongminpark417/GIDS/assets/60038680/81c14286-1e50-4335-b279-ff2cdaf0b13c)

- for institute/node_feat.npy :
![image](https://github.com/jeongminpark417/GIDS/assets/60038680/40fdfeaf-9161-4d45-8b03-d15586119716)

**Comment by WWWzq-01** [comment]
Is the accuracy still low?

**Comment by WWWzq-01** [comment]
Have you removed the `--offset 128` in `run_BaM_IGB.sh`?

**Comment by smallgrape14** [comment]
@WWWzq-01  Thank you very much ！！！
When I remove the `--offset 128` from run_BaM_IGB.sh ,
the accuracy is normal (70.11%)  , and the result of GIDS is also normal （69.49%）.
Thank you again for your help！！！
